version: "3.8"

services:
  ibeam:
    image: voyz/ibeam:latest
    ports:
      - "5000:5000"  # belül is kell, de csak proxy használja
    volumes:
      - ./inputs:/srv/inputs:ro
      - ./outputs:/srv/outputs
    environment:
      IBEAM_ACCOUNT: ${IBEAM_ACCOUNT}
      IBEAM_PASSWORD: ${IBEAM_PASSWORD}
    restart: always

  proxy:
    image: nginx:alpine
    ports:
      - "7676:80"  # kívül 7676-on fogad, belül 80-ra megy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ibeam
    restart: always
